---
Name: IanSimpson
After: framework/routes#coreroutes
---
Director:
  rules:
    'oauth': 'IanSimpson\OauthServerController'
Injector:
  Logger:
    class: 'Logger'
    factory: 'IanSimpson\LogFactory'
