---
Name: IanSimpson
After: framework/routes#coreroutes
---
Director:
  rules:
    'oauth': 'IanSimpson\OauthServerController'
IanSimpson\OauthServerController:
  privateKey: '../private.key'
  publicKey: '../public.key'
  encryptionKey: ''
