---
Name: IanSimpson
After: framework/routes#coreroutes
---
Silverstripe\Control\Director:
  rules:
    'oauth': IanSimpson\OAuth2\OauthServerController
IanSimpson\OAuth2\OauthServerController:
  privateKey: '../private.key'
  publicKey: '../public.key'
  encryptionKey: ''
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IanSimpson\OAuth2\Admin\ClientAdmin
    - IanSimpson\OAuth2\Admin\ScopeAdmin
